### PR TITLE
Print as many errors as received (issue #117)

### LINKED ISSUE #117: Print as many errors as received
When a new request command returns an error, several messages can be available in the response packet.
Currently, it only shows the first one; the rest only can be shown in debug mode, looking for the raw response.

# Expected Behavior

Ideally, all messages retrieved should be shown to customer.

# Current Behavior

# Possible Solution

# Steps to Reproduce (for bugs)

    1.
    2.
    3.
    4.

# Context and environment

### PR DESCRIPTION
**Pull request by pcantera**
Closes #117

# Description

Sample case:
So far, It's required to run in debug mode in order to see all error messages:
> DEBU[0000] Response : {"errors":{"base":["Template cannot be deployed in the selected zone."],"server_plan":["can't be blank"],"cloud_account":["can't be blank"],"name":["is already taken"],"specific_image_id":["can't be blank"],"server_plan_id":["can't be blank"],"cloud_account_id":["can't be blank"]}} 
> DEBU[0000] Status code: (422) 422 Unprocessable Entity  
> [...]
> **ERROR: Couldn't create server**
>  **-> HTTP request failed: (422) [base Template cannot be deployed in the selected zone.]**

=> From now on:

- all available error messages are shown to customer:

> **ERROR: Couldn't create server**
>  **-> HTTP request failed: (422) [#base:Template cannot be deployed in the selected zone.#server_plan:can't be blank#cloud_account:can't be blank#name:is already taken#specific_image_id:can't be blank#server_plan_id:can't be blank#cloud_account_id:can't be blank]**

- Simple error case:
>  **-> HTTP request failed: (422) [#name:is already taken]**

- Multiple messages error case:
>  **-> HTTP request failed: (422) [#server_plan:can't be blank,invalid value#cloud_account:can't be blank]**

_Additional_: Remove unused code

# Related Issue

# Motivation and Context

# How Has This Been Tested?

# Screenshots (if appropriate)

# Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

# Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by lttito — APPROVED** [review]
:+1:

File: utils/utils.go [hunk 1]
```diff
@@ -150,13 +151,14 @@ func CheckStandardStatus(status int, mesg []byte) error {
 
 		message = ScrapeErrorMessage(message, scrapResponse)
 		result := strings.Split(message, ",")
-		if result != nil && len(result) >= 1 {
-			message = result[0]
+		// concatenate as many errors as received
+		subMessages := make([]string, 0)
```
Comment (pbanos) [inline utils/utils.go]:
```suggestion
		var subMessages []string
```

File: utils/utils.go [hunk 2]
```diff
@@ -150,13 +151,14 @@ func CheckStandardStatus(status int, mesg []byte) error {
...
+		for i, val := range result {
+			// Separate into fields with func.
+			fields := strings.FieldsFunc(val, f)
+			subMessages = append(subMessages, strings.Join([]string{strconv.Itoa(i), strings.Join(fields[:], " ")}, "# "))
```
Comment (pbanos) [inline utils/utils.go]: This line is far too complex, don't abuse strings.Join and use fmt.Sprintf instead

**Review by pbanos — CHANGES_REQUESTED** [review]
Also, I'd JSON-decode the message instead for working with strings.FieldFunc

File: utils/utils.go (hunk 1 above)
Comment (pcantera) [reply utils/utils.go]: Done as well as deeper changes

File: utils/utils.go (hunk 2 above)
Comment (pcantera) [reply utils/utils.go]: Done as well as deeper changes

File: utils/utils.go [hunk 3]
```diff
@@ -81,88 +32,44 @@ func Untar(ctx context.Context, source, target string) error {
...
+				subMessages := value.([]interface{})
+				composedMsg := ""
+				if len(subMessages) > 1 {
+					// several error messages per field
+					for _, m := range subMessages {
+						if composedMsg != "" {
+							composedMsg = fmt.Sprintf("%s,%s", composedMsg, m)
+						} else {
+							composedMsg = fmt.Sprintf("%s", m)
+						}
```
Comment (pbanos) [inline utils/utils.go]: Actually, I'd keep strings.Join here, the whole body of the line 50 loop can reduced to:
```Go
  composedMsg := strings.Join(subMessages, ",")
  message = fmt.Sprintf("%s#%s:%s", message, key, composedMsg)
```

**Review by pbanos — APPROVED** [review]

File: utils/utils.go (hunk 3 above)
Comment (pcantera) [reply utils/utils.go]: good point :100: but since 'Join' requires an []string array, a conversion is needed. At any case, I'd prefer you proposal, and based on it, this proposal: 


```
subMessages := make([]string, len(value.([]interface{})))
for i, v := range value.([]interface{}) {
      subMessages[i] = fmt.Sprint(v)
}
composedMsg := strings.Join(subMessages, ",")
message = fmt.Sprintf("%s#%s:%s", message, key, composedMsg)
```

**Review by sjpatino — APPROVED** [review]
:+1:

File: utils/utils.go (hunk 3 above)
Comment (chris-m-h) [reply utils/utils.go]: Maybe a strings.Builder could be used

File: utils/utils.go [hunk 4]
```diff
@@ -81,88 +32,44 @@ func Untar(ctx context.Context, source, target string) error {
...
+					}
+				} else {
+					// only one error message per field
```
Comment (chris-m-h) [inline utils/utils.go]: If I understand it correctly, no separate treatment of len == 1 needed

**Review by chris-m-h — APPROVED** [review]
Looks good. Just a small comment

File: utils/utils.go (hunk 3 above)
Comment (pcantera) [reply utils/utils.go]: Updated code based on proposal

File: utils/utils.go (hunk 4 above)
Comment (pcantera) [reply utils/utils.go]: It basically was for improving visibility, but with new code this is removed
